{% set name = "dos2unix" %}
{% set version = "7.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://waterlan.home.xs4all.nl/{{name}}/{{name}}-{{ version }}.tar.gz
    sha256: 1cd58a60b03ed28fa39046102a185c5e88c4f7665e1e0417c25de7f8b9f78623

build:
  skip: true   # [win]
  number: 0
  script:
    - make prefix=$PREFIX all
    - make prefix=$PREFIX install

requirements:
  build:
    - {{ compiler ('c') }}
    - make
    - gettext
test:
  commands:
    - dos2unix -h
    - unix2dos -h

about:
  home: https://waterlan.home.xs4all.nl/dos2unix.html
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: "Convert text files with DOS or Mac line breaks to Unix line breaks and vice versa."

extra:
  recipe-maintainers:
    - adbeda
    - oblute
    - rluria14
