{% set name = "dos2unix" %}
{% set version = "7.5.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}-{{ version }}.tar.gz/download
    fn: {{ name }}-{{ version }}.tar.gz
    sha256: 63650acbd0c7fa8623429bcbf93a888e3351a1cad0f556cf41876f5673dd7d0b

build:
  number: 0
  script:
    - make prefix=$PREFIX all                    # [linux]
    - make prefix=$PREFIX install                # [linux]
    # disable for osx use of NLS ... need to adjust link root
    - make prefix=$PREFIX all ENABLE_NLS=        # [osx]
    - make prefix=$PREFIX install ENABLE_NLS=    # [osx]
    - nmake prefix="%PREFIX%" /f vc.mak clean    # [win]
    - nmake prefix="%PREFIX%" /f vc.mak          # [win]
    - nmake prefix="%PREFIX%" /f vc.mak install  # [win]
requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - make                 # [unix]
    - gettext              # [linux]

test:
  commands:
    - dos2unix -h
    - unix2dos -h

about:
  home: https://sourceforge.net/p/dos2unix/dos2unix/ci/master/tree
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: "Convert text files with DOS or Mac line breaks to Unix line breaks and vice versa."
  description: |
    The Dos2unix package includes utilities dos2unix and unix2dos to convert
    plain text files in DOS or Mac format to Unix format and vice versa.
  doc_url: https://sourceforge.net/p/dos2unix/dos2unix/ci/master/tree
  dev_url: https://sourceforge.net/p/dos2unix/dos2unix/ci/master/tree

extra:
  recipe-maintainers:
    - adbeda
    - oblute
    - rluria14
    - katietz
